version: 2
models:
  - name: int_nyc__trip_zone
    description: "Trips joined to pickup zone with useful derived columns"
    columns:
      - name: pickup_at
        tests: [not_null]
      - name: pickup_zone
        description: "Resolved zone for pickup_location_id"
      - name: trip_duration_min
        description: "Duration in minutes; non-negative due to sanity filter"
