SELECT
  vendorid AS vendor_id,
  pickup_datetime AS pickup_at,
  dropoff_datetime AS dropoff_at,
  store_and_fwd_flag,
  ratecodeid,
  pulocationid AS pickup_location_id,
  dolocationid AS dropoff_location_id,
  passenger_count,
  trip_distance,
  fare_amount,
  extra,
  mta_tax,
  tip_amount,
  tolls_amount,
  ehail_fee,
  improvement_surcharge,
  total_amount,
  payment_type,
  trip_type,
  congestion_surcharge,
  airport_fee,
  cab_type,
  YEAR(pickup_datetime) AS pickup_year,
  MONTH(pickup_datetime) AS pickup_month,
  DAY(pickup_datetime) AS pickup_day,
  filename_loaded,
  load_timestamp
FROM {{ source('nyc_taxi_db', 'trip_data') }}
