version: 2

sources:
  - name: nyc_taxi
    description: "Canonical raw NYC Taxi datasets across engines."

    database: >
      {% if target.type in ['snowflake', 'redshift'] %}
        NYC_TAXI_DEV
      {% elif target.type in ['spark', 'databricks'] %}
        nyc_taxi_wh
      {% elif target.type == 'bigquery' %}
        {{ env_var('BQ_PROJECT', 'my_bq_project') }}
      {% else %}
        nyc_taxi_db
      {% endif %}

    schema: >
      {% if target.type in ['snowflake', 'redshift'] %}
        RAW_ICEBERG
      {% elif target.type in ['spark', 'databricks'] %}
        nyc_taxi_wh
      {% elif target.type == 'bigquery' %}
        raw_nyc_taxi
      {% else %}
        public
      {% endif %}

    tables:
      - name: trip_data

      - name: taxi_zone_lookup
        description: "NYC taxi zone reference table with borough and service zone."
