
name: 'N_Letaxity'
config-version: 2
version: '1.0.0'

profile: 'zen_clarity'

models:
  N_Letaxity:
    +materialized: view
    staging:
      +schema: dev_viper
    intermediate:
      +schema: dev_viper
    marts:
      +schema: dev_viper


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
