
name: 'N_LeTaxity'
config-version: 2
version: '1.0.0'

profile: 'zen_clarity'

models:
  N_LeTaxity:
    +materialized: view
    staging:
    intermediate:
    marts:
    


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
