version: 2

sources:
  - name: nyc_taxi_db
    description: "Raw NYC Taxi datasets (historical + streaming)."
    schema: batch_data

    tables:
      - name: trip_data
      - name: taxi_zone_lookup

      # Streaming (lives in `public`)
  - name: nyc_taxi_stream          # <-- new source for streaming
    database: nyc_taxi_db
    schema: public
    tables:
      - name: taxi_streaming_trips
        identifier: taxi_streaming_trips
        loaded_at_field: inserted_at