version: 2

sources:
  - name: nyc_taxi_db
    description: "Raw NYC Taxi datasets (historical + streaming)."
    # Use target-specific database/schema mapping
    database: "{% if target.type == 'spark' %}{% else %}nyc_taxi_db{% endif %}"
    schema: "{% if target.type == 'spark' %}nyc_taxi_db{% else %}batch_data{% endif %}"

    tables:
      - name: trip_data
      - name: taxi_zone_lookup

  # Streaming source
  - name: nyc_taxi_stream
    database: "{% if target.type == 'spark' %}{% else %}nyc_taxi_db{% endif %}"
    schema: "{% if target.type == 'spark' %}nyc_taxi_db{% else %}public{% endif %}"
    tables:
      - name: taxi_streaming_trips
        identifier: taxi_streaming_trips
        loaded_at_field: inserted_at
